### ISSUE TITLE
Pipline as YAML  fails to run if user trigger it with Replay option

### ISSUE THREAD

**Issue by sunishsurendrank** [jenkinsci/pipeline-as-yaml-plugin#32]
I have created a Pipeline in YAML as shown below.
```
pipeline:
    agent:
      any:
    stages:
     - stage: "Checkout"
       steps:
         script: 
           - git 'https://github.com/sunishsurendrank/API.git'
     - stage: "Build Multi stage Docker Image"
       steps:
         script: 
           - sh "docker build -t sunishsurendrank/webserver:v$BUILD_NUMBER ."
```

The pipeline when successful when I build it. But failing when I replay it with the below error.

```
Replayed #40
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.LinkedHashMap
	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.parsers.PipelineParser.parse(PipelineParser.java:34)
Caused: org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.exceptions.PipelineAsYamlRuntimeException: java.lang.String cannot be cast to java.util.LinkedHashMap
	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.parsers.PipelineParser.parse(PipelineParser.java:53)
	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.cps.PipelineCpsFlowDefinition.create(PipelineCpsFlowDefinition.java:41)
	at org.jenkinsci.plugins.workflow.multibranch.yaml.pipeline.PipelineAsYamlScriptFlowDefinition.create(PipelineAsYamlScriptFlowDefinition.java:56)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```
     

**To Reproduce**
To reproduce this issue please create a Pipeline using YAML and try to run via replay.

**Expected behavior**
The pipeline should be successful.

**Comment by aytuncbeken** [comment]
Hi @sunishsurendrank ,

Thanks for reporting this bug. I opened PR to workflow-cps for some changes. After these changes are applied, I will be able to fix this error.

**Comment by sunishsurendrank** [comment]
Is this issue fixed!

**Comment by DanjelTahko** [comment]
I have this same error

**Comment by sunishsurendrank** [comment]
@DanjelTahko I am not sure this issue is fixed yet @aytuncbeken can you provide some update?

**Comment by adev101** [comment]
I see still same error. Plugin I added is   Pipeline As YAML (Incubated) Version192.vc72d50cb_c258

**Comment by jonesbusy** [comment]
PR are welcome

Nobody is actively contributing to this plugin. Recent contribution like https://github.com/jenkinsci/pipeline-as-yaml-plugin/pull/77 were only there to make it work with recent jenkins version

**Comment by ashishshaji** [comment]
issue is still present, unable to run yml files as script. can anyone suggest a jenkin version where this plugin (pipeline as yaml) works
